### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/statscache#14]
Here's an initial checklist of things we should have before we go to production (gathered from [this blogpost](http://threebean.org/blog/statscache/))
- [ ] New plugins of all kinds. What kinds of running stats/metrics would be interesting?
- [ ] By writing plugins that will flex the API of the framework, we want to find edge cases that cannot be easily coded. With those we can in turn adjust the framework now -- early -- instead of 6 months from now when we have other code relying on this.
- [ ] A set of example visualizations would be nice. I don't think statscache should host or serve the visualization, but it will help to build a few toy ones in an examples/ directory to make sure the statscache API can be used sanely. We've been doing this with a statscache branch of the releng dash repo.
- [ ] Unit/functional test cases. We have some, but could use more.
- [ ] Stress testing. With a handful of plugins, how much does the backend suffer under load?
- [ ] Plugin discovery. It would be nice to have an API endpoint we can query to find out what plugins are installed and active on the server.
- [ ] Chrome around the web interface? It currently serves only JSON responses, but a nice little documentation page that will introduce a new user to the API would be good (kind of like datagrepper itself).
- [ ] A deployment plan. We're pretty good at doing this now so it shouldn't be problematic.

**Comment by rtnpro** [comment]
Aye, :+1:
